### ISSUE TITLE
idea for another role

### ISSUE THREAD

**Issue by IPvSean** [ansible-cloud/share_ami#1]
from Mike Savage: What would be cool is to be able to have a playbook that allows you to specify an AMI ID and then a list of what regions you wanted it copied to within your own account

**Comment by scottharwell** [comment]
@IPvSean was this one of the roles that you were proposing we move into the content lab?  Looks like a good use case to me.

**Comment by IPvSean** [comment]
this will be a lot more difficult to move now b/c I already have this all synced into galaxy here: https://galaxy.ansible.com/ansible_cloud/share_ami 

you can read the documentation on the README.md here to see what you think

**Comment by IPvSean** [comment]
this role is now the ansible-cloud.share_ami.copy role, and built-in to the collection
